version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_DB: EcommerceInstant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dipesh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # PostgreSQL port
    expose:
      - "5432:5432"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommerce_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ port
      - "15672:15672"  # RabbitMQ management UI
    expose:
      - "5672"
      - "15672"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    #image: ghcr.io/dipeshdeula/ecommercein:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    restart: always
    environment:
      # Database Connection
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=EcommerceInstant;Username=postgres;Password=dipesh;
      # JWT Settings (ADDED: Missing JWT configuration)
      - JwtSettings__Key=AQUCIKBROWNFOXJUMPSOVERALAZYDOG=@34
      - JwtSettings__Issuer=EcommerceInstant
      - JwtSettings__Audience=EcommerceInstant
      - JwtSettings__ExpirationMinutes=60

      # API Settings
      - ApiSettings__BaseUrl=https://110.34.2.30:5010/api/signalr/

      # File Upload Settings (ADDED: Missing file configuration)
      - FileSettings__BaseUrl=http://110.34.2.30:5013
      - FileSettings__Root=wwwroot
      - FileSettings__FileLocation=uploads

       # SMTP Settings
      - Smtp__Host=smtp.gmail.com
      - Smtp__Port=587
      - Smtp__Username=deuladipesh94@gmail.com
      - Smtp__Password=sdgw pgxy yzeg expx

      # Email Settings
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__FromEmail=getinstantmart.contactus@gmail.com
      - EmailSettings__FromPassword=pzev elzr lpsk fwuh
      - EmailSettings__FromName=GetInstantMart
      - EmailSettings__EnableSsl=true
      - EmailSettings__Timeout=30000

          
      # Business Settings
      - BusinessSettings__CompanyName=GetInstantMart
      - BusinessSettings__CompanyTagline=Fast delivery, great service, every time.
      - BusinessSettings__SupportEmail=support@getinstantmart.com
      - BusinessSettings__SupportPhone=+977-XXX-XXXX
      - BusinessSettings__WebsiteUrl=https://getinstantmart.com
      - BusinessSettings__DefaultDeliveryTimeMinutes=25
      - BusinessSettings__BusinessHours__Start=08:00
      - BusinessSettings__BusinessHours__End=22:00
      - BusinessSettings__BusinessHours__Timezone=Asia/Kathmandu
          
      # OTP Settings
      - OtpSettings__ExpirationMinutes=5
      

      # RabbitMQ Settings
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__QueueName=ReserveStockQueue
      - RabbitMQ__OrderPlacedQueue=OrderPlacedQueue
      - RabbitMQ__OrderConfirmedQueue=OrderConfirmedQueue
      - RabbitMQ__Ssl=false
      - RabbitMQ__Uri=

      # Google Auth
      - Google__ClientId=1081137863319-s1t3r18jk69v0tvni1eirdidv550no7j.apps.googleusercontent.com

       # Payment Gateway Settings
      - PaymentGateways__Environment=Development
      - PaymentGateways__Khalti__SecretKey=5b48047469254382a3c858b083c80991
      - PaymentGateways__Khalti__BaseUrl=https://dev.khalti.com/api/v2/
      - PaymentGateways__Esewa__MerchantId=EPAYTEST
      - PaymentGateways__Esewa__SecretKey=8gBm/:&EnhH.1/q
      - PaymentGateways__Esewa__BaseUrl=https://rc-epay.esewa.com.np
      
        # Application Settings
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./uploads:/app/uploads
      - ./wwwroot:/app/wwwroot  # ADDED: Map wwwroot directory

   # pgAdmin Web GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5014:80"
    depends_on:
      - postgres
    networks:
      - ecommerce-network


  # Nginx Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    container_name: ecommerce_nginx
    restart: always
    ports:
      - "5013:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
      - ./wwwroot:/var/www/wwwroot  # ADDED: Map wwwroot for static files

    depends_on:
      - backend
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: